### ISSUE TITLE
The horrible blue background color..

### ISSUE THREAD

**Issue by isaksamsten** [dsv-data-science/dsv-data-science.github.io#1]
Dear maintainers,

We need to talk about the new blue background color of the previous nicely gray boxes. Quite honestly it is horrible and needs to be reverted 😱

I vote to have @luiseduve responsible for the design language

**Comment by panagpap** [comment]
haha yes! The blue should change to sth lighter. But definitely not gray…that was boring.

**Comment by luisqtr** [comment]
I preferred the gray boxes as well. But I can't overrule the leader. I also don't think I am the best with visual design matters tbh.

**Comment by panagpap** [comment]
I asked the web development expert of the group about his opinion and he is now coming up with a new solution! Stay tuned :-)

**Comment by zedshape** [comment]
What? Can anyone give me a right to submit?

**Comment by luisqtr** [comment]
Done!
